package(default_visibility = ["//visibility:public"])

load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "YAFL",
    srcs = ["base.cc",
            "base.h"
           ],
    hdrs = ["base.h"],
    deps = ["@cfitsio//:cfitsio"]
)
