name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest 
            type: linux
          - os: macos-latest
            type: darwin
    
    steps:
    - name: Checkout github repo (+ download lfs dependencies)
      uses: actions/checkout@v1
      with:
        lfs: true
    
    - name: Checkout lfs objects
      run: git lfs checkout

    - name: Mount bazel cache
      uses: actions/cache@v1
      with:
        path: "/home/runner/.cache/bazel"
        key: bazel

    - name: Install bazelisk
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.14.0/bazelisk-${{ matrix.type }}-amd64"
        mkdir -p "${GITHUB_WORKSPACE}/bin/"
        mv bazelisk-${{ matrix.type }}-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
        chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

    - name: Test
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" run //tests:test
        
